version: '3.1'
services:

  db-init:
    image: boxfuse/flyway:5.2.4
    depends_on:
       - db
    environment:
      - PGUSER=docker
      - PGPASSWORD=P@ssw0rd
      - PGDATABASE=main
    volumes:
      - ./db/migrations:/opt/migrations
      - ./db/scripts:/opt/scripts
    entrypoint: ["bash", "/opt/scripts/migrate.sh", "-wait", 
                 "tcp://localhost:5432", "-timeout", "15s", 
                 "--", "flyway"]

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=main
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
